version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

    command: sh -c "npm install && npm start" 
    restart: always
    ports:
      - "3000:3000"

