version: '3.8'
services:
  app:
    image: node:14
    working_dir: ./
    volumes:
      - .:/
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"